---
title: "永远不会达到的值，因为 catch 块&lt;name1&gt;继承&lt;name2&gt;&quot; |Microsoft 文档"
ms.date: 2015-07-20
ms.prod: .net
ms.technology:
- devlang-visual-basic
ms.topic: article
f1_keywords:
- BC42029
- vbc42029
helpviewer_keywords:
- BC42029
ms.assetid: 4bc84a84-ec7e-49db-8794-4fb71d36d5c0
caps.latest.revision: 12
author: dotnet-bot
ms.author: dotnetcontent
translation.priority.ht:
- de-de
- es-es
- fr-fr
- it-it
- ja-jp
- ko-kr
- ru-ru
- zh-cn
- zh-tw
translation.priority.mt:
- cs-cz
- pl-pl
- pt-br
- tr-tr
translationtype: Machine Translation
ms.sourcegitcommit: a06bd2a17f1d6c7308fa6337c866c1ca2e7281c0
ms.openlocfilehash: 2c7f180b2221b5aa6814629a5a8cd9b9d7f9fb1b
ms.lasthandoff: 03/13/2017

---
# <a name="39catch39-block-never-reached-because-39ltname1gt39-inherits-from-39ltname2gt39"></a>永远不会达到的值，因为 catch 块&lt;name1&gt;继承&lt;name2&gt;
从未到达代码中的 `Catch` 块。  
  
 默认情况下，此消息是一个警告。 有关隐藏警告或将警告视为错误的详细信息，请参阅[在 Visual Basic 中配置警告](https://docs.microsoft.com/visualstudio/ide/configuring-warnings-in-visual-basic)。  
  
 **错误 ID：** BC42029  
  
## <a name="to-correct-this-error"></a>更正此错误  
  
-   删除无关的 `Catch` 块。  
  
## <a name="see-also"></a>另请参阅  
 [如何︰ 对代码进行尝试测试...在 Visual Basic 中 catch 块](http://msdn.microsoft.com/en-us/8368e205-ed73-4185-a247-af84fb4fafa9)   
 [Try...Catch...Finally 语句](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
